future_to_the_back/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/image/', views.profile_image, name='profile_image'),
    path('<str:username>/follow/', views.follow, name='follow'),
]

future_to_the_back/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', lambda req: redirect('/movies/')),
    # path('', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

future_to_the_back/movies/urls.py
from django.urls import path
from . import views


app_name= "movies"

urlpatterns = [
    path('', views.home, name="home"),
    path('movies/', views.movies, name="movies"),
    path('search/', views.search, name="search"),
    # path('make/', views.makeMovie, name=""),
    path('<int:movie_id>/', views.moviedetail, name="moviedetail"),
    path('article/', views.article, name="article"),
]

future_to_the_back/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('', views.reviews, name='reviews'),
    path('<int:movie_id>/create/', views.create_review, name='create_review'),
    path('<int:review_id>/', views.detail, name='detail'),
    path('<int:review_id>/update/', views.update, name='update'),
    path('<int:review_id>/delete/', views.delete, name='delete'),
    path('<int:review_id>/like/', views.like, name='like'),
    path('<int:review_id>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

future_to_the_back/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

class User(AbstractUser):
    followers = models.ManyToManyField('self', symmetrical=False, related_name='followings')
    profile_image = ProcessedImageField(
        upload_to='%Y/%m/%d/',
        blank=True, 
        format='JPEG',
        processors=[Thumbnail(300, 200)],
        options={'quility' : 90}
    )

    def __str__(self):
        return self.username

future_to_the_back/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django import forms


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name',)

class CustomUserProfileChangeForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ['profile_image']

future_to_the_back/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import (
    CustomUserCreationForm,
    CustomUserChangeForm,
    CustomUserProfileChangeForm
)
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
)
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_http_methods, require_POST

from django.contrib.auth import update_session_auth_hash
from django.http import JsonResponse

from django.contrib import messages
from random import *



@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:home')
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            if not user.profile_image :
                base = '../static/images/'
                color = ['blue', 'dblue', 'ivory', 'orange','pink','purple','red','violet','yellow']
                rest = '-leather.jpg'
                idx = randint(0, len(color)-1)
                profiledefault = base + color[idx]+ rest
                user.profile_image = profiledefault
                user.save()
            auth_login(request,user)
            messages.info(request, '👍 Signup Success 😍')
            return redirect(request.GET.get('next') or 'movies:home')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
        'form_name': "회원가입",
        'button_name' : 'SIGN UP',
    }
    return render(request, 'accounts/form.html', context)





@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:home')

    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            print(request.GET.get('next'))
            messages.info(request, '✔ Login success 👏')
            return redirect(request.GET.get('next') or 'movies:home')
    else:
        form = AuthenticationForm()
    context = {
        'form' : form,
        'form_name': "로그인",
        'button_name' : 'LOG IN',
    }
    return render(request, 'accounts/form.html', context)


@login_required
# @require_POST
def logout(request):
    auth_logout(request)
    messages.info(request, '🙌 Logout Success 🤦‍♀️')
    print(request.GET.get('next'))
    return redirect(request.GET.get('next') or 'movies:home')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.info(request, 'updated success')
            return redirect('accounts:profile', request.user)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
        'form_name': "회원정보변경",
        'button_name' : 'UPDATE',
    }
    return render(request, 'accounts/form.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.info(request, 'change password success')
            return redirect('accounts:profile', request.user.username)
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
        'form_name': "비밀번호변경",
        'button_name' : 'UPDATE',
    }
    return render(request, 'accounts/form.html', context)



def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    context = {
        'person' : person,
        'form' : CustomUserProfileChangeForm()
    }
    return render(request, 'accounts/profile.html', context) 


@require_POST
def profile_image(request, username):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    form = CustomUserProfileChangeForm(request.POST, request.FILES,instance=request.user) 
    if form.is_valid():
        form.save()
    else:
        form =  CustomUserProfileChangeForm(instance=request.user)

    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person' : person,
        'form' : form,
    }
    return render(request, 'accounts/profile.html', context) 


@require_POST
def follow(request, username):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    you = get_object_or_404(get_user_model(), username=username)
    me = request.user
    print(you.followers)
    if me != you:
        if you.followers.filter(pk=me.pk).exists():
            you.followers.remove(me)
            is_follower = False
        else:
            you.followers.add(me)
            is_follower = True
        data = {
            'user_name':username,
            'is_follower':is_follower,
            'follower_count' : you.followers.count(),
            'following_count' : you.followings.count(),
        }
        return JsonResponse(data)
    return redirect('accounts:profile', username)

future_to_the_back/accounts/templates/accounts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div class="container formcontainer" style="margin-top:100px;">
    <div class="d-flex justify-content-center">
      <div class="p-2 formdiv">
        <h1 class="m-3 formtitle">{{ form_name }}</h1>
        <form action="" method="POST" class="d-flex flex-column align-items-stretch form-inner-box">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="hidden" name="next" value="{{ next }}">
          <div class="d-flex justify-content-center">
            <button onclick="history.back(-1);" class="cumstom-button form-button align-self-center " style="margin-top:20px;color:rgb(247, 220, 17);background-color:rgb(181, 13, 19) !important;">cancel</button>
            <button class="cumstom-button form-button align-self-center ml-5" style="margin-top:20px;">{{ button_name }}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

future_to_the_back/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <div class="container detailcontainer mt-5" style="max-width:900px;">

    <header class="row d-flex p-3">
      <!--profile 사진-->
      <section class="col-4 d-flex flex-column">
        {% if person.profile_image %}
          <div class="mx-auto profile-container"><img class="profile-photo" src="{{ person.profile_image.url }}" alt="{{ person.profile_image}}"></div>
        {% else %}
          <div class="mx-auto profile-container"><img class="profile-photo" src="{% static 'images/profile_dft.png' %}"  alt=""></div>
        {% endif %}

        {% if request.user == person %}
          <form class="d-flex align-self-center" style="position:absolute; bottom:0;" action="{% url 'accounts:profile_image' request.user %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <label for="id_profile_image"  title="프로필 이미지 변경" class=" input-file-button d-flex align-items-center justify-content-center">
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-camera icon" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M15 12V6a1 1 0 0 0-1-1h-1.172a3 3 0 0 1-2.12-.879l-.83-.828A1 1 0 0 0 9.173 3H6.828a1 1 0 0 0-.707.293l-.828.828A3 3 0 0 1 3.172 5H2a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1zM2 4a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2h-1.172a2 2 0 0 1-1.414-.586l-.828-.828A2 2 0 0 0 9.172 2H6.828a2 2 0 0 0-1.414.586l-.828.828A2 2 0 0 1 3.172 4H2z"/>
                <path fill-rule="evenodd" d="M8 11a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5zm0 1a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                <path d="M3 6.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
              </svg>
            </label>
            <input class=" form-control-file" title="수정" style="display:none" type="file" name="profile_image" style="color:transparent;" accept="image/*" id="id_profile_image">
             {% comment %} {% bootstrap_form form layout='inline'%} {% endcomment %}
            <input value="완료" class=" input-file-button" type="submit">
          </form>
        {% endif %}
      </section>

    
      <section class="col-8">
        <!--ID, follow버튼, 설정-->
        <div class="d-flex align-items-center">
          <p class="m-0" style="font-size:2rem;">{{ person.username }}</p>
          {% if request.user.is_authenticated %}
            {% if request.user != person %}
                <form id="followBtnForm" data-personName="{{person.username}}" action="{% url 'accounts:follow' person.username %}" method="POST">
                  {% csrf_token %}
                  {% if request.user in person.followers.all %}
                    <button class="btn btn-outline-secondary ml-3 followBtn">UNFOLLOW</button>
                  {% else %}
                    <button class="btn btn-primary ml-3 followBtn">FOLLOW</button>
                  {% endif %}
                </form>
            <!--나의 프로필 화면-->
            {% else %}
              <form action="{% url 'accounts:update' %}" method="">
                <button class="btn btn-outline-secondary follow ml-3" style="color:black;"><b>프로필편집</b></button>
              </form>
            {% endif %}
          {% else %}
              <div class="p-3">
                <a href="{% url 'accounts:login' %}"><p class="m-0" style="font-weight:lighter;">로그인 하고 팔로우 하기</p></a>
              </div>
          {% endif %}
        
        </div> 
        <!--게시물 수, 팔로워 수, 팔로잉 수-->
        <div>
          <ul class="d-flex my-2 p-1" style=""> <!--margin-rignt=40px;-->
            <li class=" mx-3" style="list-style-type: none;"><b>게시물 </b> {{ person.reviews.count }}</li>
            <li class=" mx-3" style="list-style-type: none;"> <b>팔로워 </b><span id="follower_count"> {{ person.followers.count}}</span></li>
            <li class=" mx-3" style="list-style-type: none;"> <b>팔로잉 </b><span id="following_count"> {{ person.followings.count}}</span></li>
          </ul>
        </div>

        <!--이름-->
        <div>
          <p><b> {{person.last_name}} {{person.first_name}} </b></p> <!--이름 입력받을때 한꺼번에입력받기-->
          <p></p>
        </div> 
      </section>
    </header>
    <hr>
    <div>
      <!--작성글-->
      <p class="mx-3 notofont" style=""><b>{{person.username}} 님이 작성한 게시글</b></p>
      <hr>
      {% if person.reviews.all|length %}
        {% for review in person.reviews.all %}
          <ul class="d-flex m-0 p-0 justify-content-start align-items-baseline" style=""> 
            <li class="review-list-item" style=""><a title="영화 자세히보기" href="{% url 'movies:moviedetail' review.movie.pk %}"><b style="font-family:notoR; color:rgb(140, 140, 140);">{{review.movie}}</a></b></li>
            <li class="review-list-item" style=""><a title="리뷰 자세히보기" style="color:black;" href="{% url 'reviews:detail' review.pk %}">{{review.title}}</a></li>
            <li class="review-list-item" style="">2020-08-28</li>
          </ul>
        {% endfor %}
      {% else %}
        <div class="p-0 empty-rv mb-3">
          <div class="d-flex flex-column justify-content-center align-items-center p-3" >
            <p class="m-0" style="font-weight:lighter;">아직 리뷰가 없어요.</p>
            <p class="m-0" style="font-weight:lighter;">첫 번째 리뷰를 남겨주세요.</p>
          </div>
        </div>
      {% endif %}
      <hr class="mt-1">
      <!-- 좋아요 글-->
      <p class="mx-3 notofont"><b>{{person.username}} 님이 좋아하는 게시글</b></p>
      <hr>

      {% if person.like_articles.all|length %}
        {% for review in person.like_articles.all %}
          <ul class="d-flex m-0 p-0 justify-content-start align-items-baseline" style=""> 
            <li class="review-list-item" style=""><a title="영화 자세히보기" href="{% url 'movies:moviedetail' review.movie.pk %}"><b style="font-family:notoR; color:rgb(140, 140, 140);">{{review.movie}}</a></b></li>
            <li class="review-list-item" style=""><a title="리뷰 자세히보기" style="color:black;" href="{% url 'reviews:detail' review.pk %}">{{review.title}}</a></li>
            <li class="review-list-item" style=""><a title="프로필 보기" style="color:black;" href="{% url 'accounts:profile' review.author.username%}">{{review.author}}</a></li>
            <li class="review-list-item" style="">2020-08-28</li>
          </ul>
        {% endfor %}
      {% else %}
        <div class="p-0 empty-rv mb-3">
          <div class="d-flex flex-column justify-content-center align-items-center p-3" >
            <p class="m-0 my-3" style="font-weight:lighter;">좋아하는 게시글이 없어요.</p>
          </div>
        </div>
      {% endif %}
      <hr class="mt-1" style="margin-bottom:0; padding-bottom:16px;">  
    </div>


{% endblock content %}

{% block script %}
  <script>


    // follow
    const followBtnForm = document.querySelector('#followBtnForm')
    followBtnForm.addEventListener('submit', (e) => {
      e.preventDefault() 

      console.log(followBtnForm.dataset)
      const personname = followBtnForm.dataset.personname
      const API_URL = `/accounts/${personname}/follow/`
      const csrftoken = document.querySelector('input[name=csrfmiddlewaretoken]').value
      const options = {headers: {'X-CSRFToken': csrftoken}} 

      axios.post(API_URL, {}, options)
        .then(res => {
          const followBtn = document.querySelector('.followBtn')
          const {is_follower, follower_count, following_count} = res.data
          const followerCount = document.querySelector('#follower_count')
          const followingCount = document.querySelector('#following_count')

          followerCount.innerText = `${follower_count}`
          followingCount.innerText = `${following_count}`
          followBtn.classList.toggle('btn-primary')
          followBtn.classList.toggle('btn-outline-secondary')
          followBtn.innerText = is_follower ? 'UNFOLLOW' : 'FOLLOW'
       })
        .catch(err => {
         console.error(err)
       })
    }) 




  </script>
{% endblock script %}

future_to_the_back/accounts/templates/accounts/profile1.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
  <div class="container detailcontainer mt-5" style="max-width:900px;">

    <header class="row d-flex p-3">
      <!--profile 사진-->
      <section class="col-4">
          {% if person.profile_image %}
            <div class="mx-auto"><img class="profile-photo" src="{{ person.profile_image.url }}" alt="{{ person.profile_image}}"></div>
          {% else %}
            <div class="mx-auto profile-container" style="width:250px; height:250px;"><img class="profile-photo" src={% static 'images/profile_dft.png' %}  alt=""></div>
          {% endif %}

          <form action="{% url 'accounts:profile_image' request.user %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form layout='inline'%}
            <input type="submit">
          </form>
      </section>

    
      <section class="col-8">
        <!--ID, follow버튼, 설정-->
        <div class="d-flex align-items-center">
          <p class="m-0" style="font-size:2rem;">{{ person.username }}</p>
          {% if request.user != person %}
            <form id="followBtnForm" data-personName="{{person.username}}" action="{% url 'accounts:follow' person.username %}" method="POST">
              {% csrf_token %}
              {% if request.user in person.followers.all %}
                <button class="btn btn-outline-secondary ml-3 followBtn">UNFOLLOW</button>
              {% else %}
                <button class="btn btn-primary ml-3 followBtn">FOLLOW</button>
            </form>

            {% endif %}
          <!--나의 프로필 화면-->
          {% else %}
            <form action="{% url 'accounts:update' %}" method="">
              <button class="btn btn-outline-secondary follow ml-3" style="color:black;"><b>프로필편집</b></button>
            </form>
            <div class="pl-3 ">
              <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-gear-wide" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M8.932.727c-.243-.97-1.62-.97-1.864 0l-.071.286a.96.96 0 0 1-1.622.434l-.205-.211c-.695-.719-1.888-.03-1.613.931l.08.284a.96.96 0 0 1-1.186 1.187l-.284-.081c-.96-.275-1.65.918-.931 1.613l.211.205a.96.96 0 0 1-.434 1.622l-.286.071c-.97.243-.97 1.62 0 1.864l.286.071a.96.96 0 0 1 .434 1.622l-.211.205c-.719.695-.03 1.888.931 1.613l.284-.08a.96.96 0 0 1 1.187 1.187l-.081.283c-.275.96.918 1.65 1.613.931l.205-.211a.96.96 0 0 1 1.622.434l.071.286c.243.97 1.62.97 1.864 0l.071-.286a.96.96 0 0 1 1.622-.434l.205.211c.695.719 1.888.03 1.613-.931l-.08-.284a.96.96 0 0 1 1.187-1.187l.283.081c.96.275 1.65-.918.931-1.613l-.211-.205a.96.96 0 0 1 .434-1.622l.286-.071c.97-.243.97-1.62 0-1.864l-.286-.071a.96.96 0 0 1-.434-1.622l.211-.205c.719-.695.03-1.888-.931-1.613l-.284.08a.96.96 0 0 1-1.187-1.186l.081-.284c.275-.96-.918-1.65-1.613-.931l-.205.211a.96.96 0 0 1-1.622-.434L8.932.727zM8 12.997a4.998 4.998 0 1 0 0-9.995 4.998 4.998 0 0 0 0 9.996z"/>
              </svg>
            </div>
          {% endif %}
        
        </div> 
        <!--게시물 수, 팔로워 수, 팔로잉 수-->
        <div>
          <ul class="d-flex my-2 p-1" style=""> <!--margin-rignt=40px;-->
            <li class=" mx-3" style="list-style-type: none;"><b>게시물 </b> {{ person.reviews.count }}</li>
            <li class=" mx-3" style="list-style-type: none;"> <b>팔로워 </b><span id="follower_count"> {{ person.followers.count}}</span></li>
            <li class=" mx-3" style="list-style-type: none;"> <b>팔로잉 </b><span id="following_count"> {{ person.followings.count}}</span></li>
          </ul>
        </div>

        <!--이름-->
        <div>
          <p><b> {{person.last_name}} {{person.first_name}} </b></p> <!--이름 입력받을때 한꺼번에입력받기-->
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione modi non porro! Libero similique quisquam molestiae veritatis, aspernatur praesentium consequatur assumenda id velit animi deserunt perferendis est ullam minima quaerat?</p>
        </div> 
      </section>
    </header>
    <hr>
    <div>
      <!--작성글-->
      <p class="mx-3 notofont" style=""><b>{{person.username}} 님이 작성한 게시글</b></p>
      <hr>
      {% if person.reviews.all|length %}
        {% for review in person.reviews.all %}
          <ul class="d-flex m-0 p-0 justify-content-start align-items-baseline" style=""> 
            <li class="review-list-item" style=""><a title="영화 자세히보기" href="{% url 'movies:moviedetail' review.movie.pk %}"><b style="font-family:notoR; color:rgb(140, 140, 140);">{{review.movie}}</a></b></li>
            <li class="review-list-item" style=""><a title="리뷰 자세히보기" style="color:black;" href="{% url 'reviews:detail' review.pk %}">{{review.title}}</a></li>
            <li class="review-list-item" style="">2020-08-28</li>
          </ul>
        {% endfor %}
      {% else %}
        <div class="p-0 empty-rv">
          <div class="d-flex flex-column justify-content-center align-items-center p-3" >
            <p class="m-0" style="font-weight:lighter;">아직 리뷰가 없어요.</p>
            <p class="m-0" style="font-weight:lighter;">첫 번째 리뷰를 남겨주세요.</p>
          </div>
        </div>
      {% endif %}
      <hr class="mt-1">
      <!-- 좋아요 글-->
      <p class="mx-3 notofont"><b>{{person.username}} 님이 좋아하는 게시글</b></p>
      <hr>

      {% if person.like_articles.all|length %}
        {% for review in person.like_articles.all %}
          <ul class="d-flex m-0 p-0 justify-content-start align-items-baseline" style=""> 
            <li class="review-list-item" style=""><a title="영화 자세히보기" href="{% url 'movies:moviedetail' review.movie.pk %}"><b style="font-family:notoR; color:rgb(140, 140, 140);">{{review.movie}}</a></b></li>
            <li class="review-list-item" style=""><a title="리뷰 자세히보기" style="color:black;" href="{% url 'reviews:detail' review.pk %}">{{review.title}}</a></li>
            <li class="review-list-item" style=""><a title="프로필 보기" style="color:black;" href="{% url 'accounts:profile' review.author.username%}">{{review.author}}</a></li>
            <li class="review-list-item" style="">2020-08-28</li>
          </ul>
        {% endfor %}
      {% else %}
        <div class="p-0 empty-rv">
          <div class="d-flex flex-column justify-content-center align-items-center p-3" >
            <p class="m-0 my-3" style="font-weight:lighter;">좋아하는 게시글이 없어요.</p>
          </div>
        </div>
      {% endif %}
      <hr class="mt-1" style="margin-bottom:0; padding-bottom:16px;">  
    </div>

  

    {% comment %} <h2>{{ person.username }}님이 좋아요한 글</h2>
    {% for article in person.like_articles.all %}
        <div>{{article.title}}</div>
    {% endfor %} {% endcomment %}
    

{% endblock content %}

{% block script %}
  <script>
    const followBtnForm = document.querySelector('#followBtnForm')
    followBtnForm.addEventListener('submit', (e) => {
      e.preventDefault() 

      console.log(followBtnForm.dataset)
      const personname = followBtnForm.dataset.personname
      const API_URL = `/accounts/${personname}/follow/`
      const csrftoken = document.querySelector('input[name=csrfmiddlewaretoken]').value
      const options = {headers: {'X-CSRFToken': csrftoken}} 

      axios.post(API_URL, {}, options)
        .then(res => {
          const followBtn = document.querySelector('.followBtn')
          const {is_follower, follower_count, following_count} = res.data
          const followerCount = document.querySelector('#follower_count')
          const followingCount = document.querySelector('#following_count')

          followerCount.innerText = `${follower_count}`
          followingCount.innerText = `${following_count}`
          followBtn.classList.toggle('btn-primary')
          followBtn.classList.toggle('btn-outline-secondary')
          followBtn.innerText = is_follower ? 'UNFOLLOW' : 'FOLLOW'
       })
        .catch(err => {
         console.error(err)
       })
    }) 
  </script>
{% endblock script %}