future_to_the_back/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    # path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/image/', views.profile_image, name='profile_image'),
    path('<str:username>/follow/', views.follow, name='follow'),
]

future_to_the_back/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', lambda req: redirect('/movies/')),
    # path('', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

future_to_the_back/movies/urls.py
from django.urls import path
from . import views


app_name= "movies"

urlpatterns = [
    path('', views.home, name="home"),
    path('movies/', views.movies, name="movies"),
    path('search/', views.search, name="search"),
    # path('make/', views.makeMovie, name=""),
    path('<int:movie_id>/', views.moviedetail, name="moviedetail"),
    path('article/', views.article, name="article"),
]

future_to_the_back/config/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'js/bootstrap.bundle.js' %}">
  <link rel="stylesheet" href="{% static 'stylesheets/style.css' %}">
  <title>FUTURE TO THE BACK</title>
</head>
<body class="background-blk">
  <nav class="navbar navbar-expand-lg navbar-bg d-flex justify-content-between sticky-top">
    <div>
      <a class="navbar-brand p-0 m-0" href="{% url 'movies:home' %}" title="메인화면으로 이동">
        <img class="logo-size" src="/static/images/FUTURE_TO_THE_BACK_LOGO.png" alt="logo">
      </a>
    </div>
   
   {% comment %} btn my-sm-0 search {% endcomment %}
    <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNav">
      <form class="form-inline my-2 my-lg-0 mx-4" action="{% url 'movies:search' %}">
        <input class="searchinput form-control mr-sm-2 " name="search" type="" placeholder="영화명을 입력하세요" aria-label="Search">
        <button class="btn my-sm-0 search" type="submit">SEARCH</button>
      </form>
      <ul class="navbar-nav mr-5">
        {% if not request.user.is_authenticated %}
          <li class="nav-item nav-item-name">
            <a class="nav-link text-white" href="{% url 'accounts:signup' %}?next={{ request.get_full_path | urlencode }}" title="회원가입">SignUp</a>
          </li>
          <li class="nav-item nav-item-name">
            <a class="nav-link text-white" href="{% url 'accounts:login' %}?next={{ request.get_full_path | urlencode }}" title="로그인">LogIn</a>
          </li>
        {% else %}
          <li class="nav-item nav-item-name">
            <a class="nav-link text-blue" href="{% url 'accounts:profile' request.user.username %}" title="나의 프로필 보기">{{request.user.username}}</a>
          </li>
          <li class="nav-item nav-item-name">
            <a class="nav-link text-white" href="{% url 'accounts:logout' %}?next={{ request.get_full_path | urlencode }}" title="로그아웃">Logout</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

{% if messages %}
  {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
      <div class="alert alert-danger alert-dismissible fade show d-flex justify-content-center" role="alert">
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %}>
          {{ message.message }}
        </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {% comment %} <img src="" style="display:none;" onerror="(function(el){ setTimeout(function(){ el.parentNode.parentNode.removeChild(el.parentNode); },2000 ); })(this);" /> {% endcomment %}
      </div>
    {% else %}
      <div class="alert alert-secondary alert-dismissible fade show d-flex justify-content-center" role="alert">
        <strong {% if message.tags %} class="{{ message.tags }}"{% endif %} style="text-align:center;">
          {{ message.message }}
        </strong> 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <img src="" style="display:none;" onerror="(function(el){ setTimeout(function(){ el.parentNode.parentNode.removeChild(el.parentNode); },2000 ); })(this);" />
      </div>
    {% endif %}
  {% endfor %}
{% endif %} 



  {% block content %}
  {% endblock content %}




  {% block script %}
  {% endblock script %}
  
  <!--axios-->
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>


  <script src="https://kit.fontawesome.com/822eec1fcb.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>