future_to_the_back/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('', lambda req: redirect('/movies/')),
    # path('', include('movies.urls')),
    path('reviews/', include('reviews.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

future_to_the_back/movies/urls.py
from django.urls import path
from . import views


app_name= "movies"

urlpatterns = [
    path('', views.home, name="home"),
    path('movies/', views.movies, name="movies"),
    path('search/', views.search, name="search"),
    # path('make/', views.makeMovie, name=""),
    path('<int:movie_id>/', views.moviedetail, name="moviedetail"),
    path('article/', views.article, name="article"),
]

future_to_the_back/reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'
urlpatterns = [
    path('', views.reviews, name='reviews'),
    path('<int:movie_id>/create/', views.create_review, name='create_review'),
    path('<int:review_id>/', views.detail, name='detail'),
    path('<int:review_id>/update/', views.update, name='update'),
    path('<int:review_id>/delete/', views.delete, name='delete'),
    path('<int:review_id>/like/', views.like, name='like'),
    path('<int:review_id>/comments/', views.create_comment, name='create_comment'),
    path('<int:review_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

future_to_the_back/movies/models.py
from django.db import models


# Create your models here.

class Movie(models.Model):
    movie_name = models.CharField(max_length=100)
    rank = models.IntegerField()
    target_dt = models.CharField(max_length=10)
    # False == old
    rank_old_and_new = models.CharField(max_length=10)
    open_dt = models.CharField(max_length=100)
    sales_share = models.FloatField()
    sales_change = models.FloatField()
    sales_acc = models.BigIntegerField()
    audi_cnt = models.IntegerField()
    audi_change = models.FloatField()
    audi_acc = models.BigIntegerField()
    scrn_cnt = models.IntegerField()
    show_cnt = models.IntegerField()

    def __str__(self):
        return "%s the place" % self.movie_name

class MovieDetail(models.Model):
    movie = models.OneToOneField(Movie, primary_key=True, on_delete=models.CASCADE)
    overview = models.TextField()
    poster = models.URLField()
    staff1 = models.CharField(max_length=50, blank=True, null=True)
    staff2 = models.CharField(max_length=50, blank=True, null=True)
    staff3 = models.CharField(max_length=50, blank=True, null=True)
    staff4 = models.CharField(max_length=50, blank=True, null=True)
    staff5 = models.CharField(max_length=50, blank=True, null=True)
    thumb_staff1 = models.URLField(blank=True, null=True)
    thumb_staff2 = models.URLField(blank=True, null=True)
    thumb_staff3 = models.URLField(blank=True, null=True)
    thumb_staff4 = models.URLField(blank=True, null=True)
    thumb_staff5 = models.URLField(blank=True, null=True)
    netizen_score = models.FloatField()
    special_score = models.FloatField()
    running_time = models.CharField(max_length=10)
    genre = models.CharField(max_length=10)
    grade = models.CharField(max_length=10)
    download_url = models.URLField(blank=True, null=True)
    best_line1_character = models.CharField(max_length=50, blank=True, null=True)
    best_line1 = models.CharField(max_length=100, blank=True, null=True)
    best_line2_character = models.CharField(max_length=50, blank=True, null=True)
    best_line2 = models.CharField(max_length=100, blank=True, null=True)
    relate_movie1 = models.CharField(max_length=50, blank=True, null=True)
    relate_movie2 = models.CharField(max_length=50, blank=True, null=True)
    relate_movie3 = models.CharField(max_length=50, blank=True, null=True)
    relate_movie4 = models.CharField(max_length=50, blank=True, null=True)
    relate_movie5 = models.CharField(max_length=50, blank=True, null=True)
    relate_movies_thumb1 = models.URLField(blank=True, null=True)
    relate_movies_thumb2 = models.URLField(blank=True, null=True)
    relate_movies_thumb3 = models.URLField(blank=True, null=True)
    relate_movies_thumb4 = models.URLField(blank=True, null=True)
    relate_movies_thumb5 = models.URLField(blank=True, null=True)
    aka_info = models.CharField(max_length=50)
    viewer_img = models.URLField(blank=True, null=True)

    def __str__(self):
        return self.movie.movie_name

future_to_the_back/movies/views.py
from django.shortcuts import render, redirect

import requests
import json
from pprint import pprint
from .models import MovieDetail, Movie
from pprint import pprint
from reviews.models import Review, Comment
from reviews.forms import Review, CommentForm
from django.contrib import messages

# Create your views here.
def search(request):
    movie_name = request.GET.get('search')
    search_movie = Movie.objects.all().filter(movie_name__startswith=movie_name)
    if search_movie:
        return redirect('movies:moviedetail', search_movie[0].id)
    else:
        messages.error(request, '😢Sorry there are no movie data 🐱‍🚀')
        return redirect('movies:home')

def movies(request):
    # home에서 받은 정보로 dt만들기
    month = request.GET.get('month')
    year = request.GET.get('year')
    day = request.GET.get('day')

    target_dt= year + month + day

    movies = []
    # movies = Movie.objects.filter(target_dt='20180428')
    movies = Movie.objects.filter(target_dt=target_dt)
    if not movies:
        messages.error(request, '😢Sorry there are no movie data at that time🐱‍🚀')
        return redirect('movies:home')

    movies_detail = []
    for i in movies:
        movies_detail.append(MovieDetail.objects.get(movie=i))

    first_rank_movie_score = movies_detail[0].netizen_score + movies_detail[0].special_score
    first_rank_movie_idx = 1
    for i in range(1, len(movies_detail)):
        score = movies_detail[i].netizen_score + movies_detail[i].special_score
        if score > first_rank_movie_score:
            first_rank_movie_score = score
            first_rank_movie_idx = i
    context = {
        'movies_detail' : movies_detail,
        'hidden_movie' : movies_detail[first_rank_movie_idx],
        'rank_1_movie_title' : movies_detail[0].movie.movie_name,
    }
    return render(request, 'movies/movies.html', context)



def moviedetail(request, movie_id):
    movie_detail = MovieDetail.objects.filter(pk=movie_id)
    movie = MovieDetail.objects.get(pk=movie_id)
    reviews = movie.review_set.all()
    context = {
        'movie_detail':movie_detail[0],
        'reviews':reviews,
        'comment_form' : CommentForm(),
    }
    return render(request, 'movies/moviedetail.html', context)




def home(request):
    return render(request, 'movies/home.html')


def article(request):
    return render(request, 'movies/_article.html')

future_to_the_back/movies/templates/movies/_article.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

 <!-- Button trigger modal -->
{% comment %} <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<a href="/1" data-toggle="modal" data-target="#exampleModal">모달모달</a> {% endcomment %}

 <!-- Modal -->
<div class="modal fade" id="post-{{ movie_detail.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="max-width:780px;" >
    <div class="modal-content d-flex flex-column" style="border-radius:0; border:none;" > 
      {% comment %} <div class="px-3 py-2" style=""><b> 리뷰 </b></div> {% endcomment %}
      <div class="p-3">
        <hr class="m-0">
        <div class="d-flex">
          <div class="p-2" style="display:relative">
            <span class="review-title">{% lorem 20 w random %} </span>
            <span class="review-title-date">2020-08-28</span>
          </div>
          {% comment %} {% if request.user != article.author %} {% endcomment %}
          <div class="d-flex flex-column justify-content-center align-self-center">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 2.748l-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
            </svg>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-heart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
            </svg>
          </div>
          {% comment %} {% else %}
          <div class="d-flex flex-column justify-content-center align-self-center">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-scissors" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M3.5 3.5c-.614-.884-.074-1.962.858-2.5L8 7.226 11.642 1c.932.538 1.472 1.616.858 2.5L8.81 8.61l1.556 2.661a2.5 2.5 0 1 1-.794.637L8 9.73l-1.572 2.177a2.5 2.5 0 1 1-.794-.637L7.19 8.61 3.5 3.5zm2.5 10a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm7 0a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
            </svg>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
              <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
            </svg>
          </div>
           {% endcomment %}
        </div>
        <hr class="m-0">
        <div class="p-1">
          {% lorem 5 b random %}
        </div>
        <div>
          {% comment %} {% if request.user != article.author %} {% endcomment %}
            <div class="d-flex justify-content-end">
            {% comment %} {% url 'reviews:update' review.id %} {% endcomment %}
            <a href="" class="btn btn-success">update</a>
            {% comment %} {% url 'reviews:delete' review.id %} {% endcomment %}
            <a href="" class="btn btn-danger">Delete</a>
          {% comment %} {% endif %} {% endcomment %}
      </div>
        </div>
         
       
      </div>
      
      <!-- 댓글 입력 -->
      <hr>
      <div class="px-3"><b>댓글  몇개 </b></div>
      <div class="container m-0 p-3" style="max-width:800px; width=100%;"> 
        <div class="row py-3">
          <!-- 댓글입력-->
          <div class="col-1">
            <div class="mini-prf-container">
              <!-- 로그인 된 유저 정보로 할 것-->
              <img class="profile-photo" src="{% static 'images/profile_default.jpg' %}" alt="profile">
            </div>
          </div>
          <div class="col-11" style="padding-left:0;">
            <form action="">
              <input class="reviewinput" type="text" style=" width=500px;" size="75">
              <button class="" name="comment">등록</button>
              <input type="reset" value="취소">
            </form>
          </div>
        </div>
        <!-- 댓글 보여주기 -->
        <div class="row py-3">
          <div class="col-1" style="">
            <div class="mini-prf-container">
              <!-- 로그인 된 유저 정보로 할 것-->
              <img class="profile-photo" src="{% static 'images/profile_default.jpg' %}" alt="profile">
            </div>
          </div>
          <div class="col-11" style="padding-left:0;">
            <p class="m-0" style="font-weight: 500;">{% lorem w random %}</p>
            <p class="m-0" style="padding-right:40px;">{% lorem 2 b random %}</p>
          </div>
        </div>
      </div>
    
    

    </div> <!-- modal-content end-->
  </div> <!-- modal dialog end-->
</div> 

{% endblock content %}


{% block script %}




{% endblock script %}

future_to_the_back/movies/templates/movies/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="d-flex justify-content-center flex-wrap container align-items-center" style="width:1200px;">
  <div class=" targettime" data-targetyear="2019" data-targetmonth="12" data-targetday="25">
    #작년 크리스마스
  </div>
  <div class=" targettime" data-targetyear="2019" data-targetmonth="02" data-targetday="13">
    #작년 발렌타인 1위가 궁금해!
  </div>
  <div class=" targettime" data-targetyear="2019" data-targetmonth="04" data-targetday="11">
    #19년 중간고사 기간
  </div>
  <div class=" targettime" data-targetyear="2018" data-targetmonth="04" data-targetday="28">
    #어벤져스 때문에 놓친 영화!
  </div>
  <div class=" targettime" data-targetyear="2019" data-targetmonth="05" data-targetday="08">
    #어버이날엔 어떤영화를 봤더라..
  </div>
  <div class=" targettime" data-targetyear="2019" data-targetmonth="08" data-targetday="15">
    #광복절 영화 복습
  </div>
</div>



  <!-- <form id="homeform" action="{% url 'movies:movies' %}" method="GET"> -->


  <form id="homeform" class="" action="{% url 'movies:movies' %}" method="GET">
    <!-- time machine -->

    <div class="container homebox1" id="destination-time" style="background-color:grey; max-width:780px; ">
      <!-- destination title-->
      <div class="row">
        <div class="col-12 my-2 d-flex justify-content-center" style="text:center;">
          <h1 class="label1 tracking-in-expand" style="">DESTINATION TIME</h1>
        </div>
      </div>

      <!-- input & tags-->
      
        <div class="row">

          <div class="col-3 d-flex flex-column justify-content-center align-items-center">
            <input class="digitalinput digitalcolor1 " type="number" id="year" name="year" min="1" max="2020" required>
            <h1 class="dymo1">YEAR</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <input class="digitalinput digitalcolor1" type="number" id="month" name="month" min="1" max="12" required>
            <h1 class="dymo1">MONTH</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <input class="digitalinput digitalcolor1" type="number" id="day" name="day" min="1" max="31" required>
            <h1 class="dymo1">DAY</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <circle cx="8" cy="8" r="8" id="amlight1" class="light-grey digitalcolor1">
            </svg>
            <h1 class="dymo1 p-0">AM</h1>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <circle cx="8" cy="8" r="8" id="pmlight1" class="light-grey digitalcolor1" >
            </svg>
            <h1 class="dymo1 p-0">PM</h1>
          
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 hour digitalcolor1" id="hour">08</p>
            <h1 class="dymo1">HOUR</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 min digitalcolor1" id="min">33</p>
            <h1 class="dymo1">MIN</h1>
          </div>


        </div> <!-- input & tag 닫는 div-->  
    </div> <!-- timemachine container 닫는 div -->


    <!-- 현재시간 정보-->

    <div class="container homebox2 " id="present-time" style="background-color:grey; max-width:780px;">
      <!-- present title-->
      <div class="row">
        <div class="col-12 my-2 d-flex justify-content-center" style="text:center;">
          <h1 class="label2 tracking-in-expand" style="">PRESENT TIME</h1>
        </div>
      </div>

      <!-- input & tags-->
      
        <div class="row">

          <div class="col-3 d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 year digitalcolor2" id="present-year">2008</p>
            <h1 class="dymo2">YEAR</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 month digitalcolor2" id="present-month">08</p>
            <h1 class="dymo2">MONTH</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 day digitalcolor2" id="present-day">08</p>
            <h1 class="dymo2">DAY</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <circle cx="8" cy="8" r="8" id="amlight2" class="light-grey digitalcolor2">
            </svg>
            <h1 class="dymo2 p-0">AM</h1>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-circle-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <circle cx="8" cy="8" r="8" id="pmlight2" class="light-grey digitalcolor2" >
            </svg>
            <h1 class="dymo2 p-0">PM</h1>
          
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 hour digitalcolor2" id="hour">08</p>
            <h1 class="dymo2">HOUR</h1>
          </div>

          <div class="col d-flex flex-column justify-content-center align-items-center">
            <p class="digitalinput m-0 min digitalcolor2" id="min">33</p>
            <h1 class="dymo2">MIN</h1>
          </div>


        </div> <!-- input & tag 닫는 div-->  
    </div> <!-- timemachine container 닫는 div -->



    <div class="container d-flex justify-content-center align-items-center">
      <button class="m-5 cumstom-button lg-button" id="button"> Let's Go! </button>
    </div>
  </form>




 
    


  

        {% comment %} #20130302 입학
        # 20150927 추석
        # 20170213 발렌타인
        # 20191225 크리스마스
        # 20180428 어벤져스

        # 20190213 발렌타인


        # 20191111 빼뺴로
        # 20190508 어버이날
        # 20190815 광복절
        # 20190411 중간고사 {% endcomment %}



{% endblock content %}


{% block script %}

  <script>
    document.getElementById("year").onkeyup= function() {
       var input=parseInt(this.value);
       if(input<0 || input>2020) {
        alert("Value should be between 0 - 2020");
        this.value = ''
       }
       return;
    }    
    document.getElementById("month").onkeyup= function() {
       var input=parseInt(this.value);
       if(input<0 || input>12) {
        alert("Value should be between 1 - 12");
        this.value = ''
       }
       return;
    }    
    document.getElementById("day").onkeyup= function() {
       var input=parseInt(this.value);
       if(input<0 || input>31) {
        alert("Value should be between 1 - 31");
        this.value = ''
       }
       return;
    }    

    function addZero (i){
      parseInt(i)
      if (i < 10) {
        i = "0" + i;
      }
      return i;
    }
    const now = new Date()

    
    //현재 시간 변수들
    const nowYear = now.getFullYear()

    const nowMonth = addZero(now.getMonth() +1)
    const nowDay = addZero(now.getDate())
    const nowHour = addZero(now.getHours())
    const nowMin = addZero(now.getMinutes())

      
    const amLight1 = document.querySelector('#amlight1')
    const pmLight1 = document.querySelector('#pmlight1') 
      
    if (nowHour >= 0 && nowHour <12) {
      amLight1.classList.replace('light-grey', 'digitalcolor1')
      pmLight1.classList.replace('digitalcolor1', 'light-grey')
      
    } else {
      amLight1.classList.replace('digitalcolor1', 'light-grey')
      pmLight1.classList.replace('light-grey', 'digitalcolor1')
    }

    const amLight2 = document.querySelector('#amlight2')
    const pmLight2 = document.querySelector('#pmlight2') 
    
    if (nowHour >= 0 && nowHour <12) {
      amLight2.classList.replace('light-grey', 'digitalcolor2')
      pmLight2.classList.replace('digitalcolor2', 'light-grey')
      
    } else {
      amLight2.classList.replace('digitalcolor2', 'light-grey')
      pmLight2.classList.replace('light-grey', 'digitalcolor2')
    }



    //현재시간
    const presentYear = document.querySelector('#present-year')
    const presentMonth = document.querySelector('#present-month')
    const presentDay = document.querySelector('#present-day')


    const Hours = document.querySelectorAll('.hour')
    const Mins = document.querySelectorAll('.min')


    presentYear.innerText = nowYear
    presentMonth.innerText = nowMonth
    presentDay.innerText = nowDay

    Hours.forEach(Hour => {
      Hour.innerText = nowHour 
    })
    Mins.forEach(Min => {
      Min.innerText = nowMin  
    })

    //목적시간
    const destinationYear = document.querySelector('#year')
    const destinationMonth = document.querySelector('#month')
    const destinationDay = document.querySelector('#day')


  

    // 시간 자동입력
    const targetDts = document.querySelectorAll('.targettime')
    targetDts.forEach(targetDt => {
      const targetYear = targetDt.dataset.targetyear
      const targetMonth = targetDt.dataset.targetmonth
      const targetDay = targetDt.dataset.targetday


      targetDt.addEventListener('click', (e) => {
        e.preventDefault()
        destinationYear.value = targetYear
        destinationMonth.value = targetMonth
        destinationDay.value = targetDay 
      })
    })




    // 타임머신 숫자 줄어드는 기능
    const button = document.querySelector('#button')
    button.addEventListener('click', (e)=> {
      e.preventDefault()
      const homeForm = document.querySelector('#homeform')

      const machine1 = document.querySelector('#destination-time')
      const machine2 = document.querySelector('#present-time')
      
      targetDts.forEach(targetDt => {
        targetDt.classList.add('shake3')
      })
      
      machine1.classList.add('shake1')
      machine2.classList.add('shake2')
      button.classList.add('shake3')
      timemachine(presentYear, destinationYear)
      timemachine(presentMonth, destinationMonth)
      timemachine(presentDay, destinationDay)
      setTimeout(() => {
        // document.querySelector('#homeform').submit()
        homeForm.submit()
      }, 2000)
    })
    



    function timemachine (present, destination) {
      var $counter = $(present),
          startVal = $counter.text(),
          currentVal,
          endVal = destination.value

      currentVal = startVal
      const i = setInterval(function ()
      {
          if (currentVal == endVal)
          {
              clearInterval(i)
          }
          else if (currentVal > endVal )
          {   
              currentVal--;
              $counter.text(addZero(currentVal))
          }
          else {
              currentVal++;
              $counter.text(addZero(currentVal))
          }
      }, 100);
    }


  </script>
{% endblock script %}

future_to_the_back/movies/templates/movies/movies.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  

  <div class="container d-flex justify-content-center">
    <h1 class="mt-2 pt-2 mb-0 pb-0" style="color:orange; text-align:center; font-family:dh;">{{ rank_1_movie_title }}
    <h1 class="mt-2 pt-2 mb-0 pb-0" style="color:white; text-align:center; font-family:dh;">에 가려진 명작 
    <a href="{% url 'movies:moviedetail' hidden_movie.movie_id %}">{{ hidden_movie.movie.movie_name }}</a></h1>
  </div>

  <div class="container moviecontainer mx-auto mt-5 d-flex flex-column justify-content-center">
    <div class="row row-cols-5 d-flex justify-content-around">
      {% for movie in movies_detail %}
        <div class="col moviecard d-flex justify-content-start">
          <div>
            <a href="{% url 'movies:moviedetail' movie.movie_id %}">
              <img class="moviecard-img" src={{movie.poster}} style="width:202.988px;height:291.39px;" alt="">
            </a>
            <div class="text-white card-list p-2 my-3" style="background-color:rgb(26, 23, 23);">
              <div class="card-list-item d-flex justify-content-between">
                <div style="color:rgb(212, 208, 208);">예매율</div>
                <div class="font-weight-bold" style="color:#B50D13;">{{ movie.movie.sales_share }}%</div>
              </div>
              <div class="card-list-item" style="font-size:0.5em; text-align:start; color:rgb(212, 208, 208);">
                {{ movie.movie.open_dt }}개봉|{{ movie.grade }} | {{ movie.genre }} 
              </div>
            </div>
          </div>
          <p class="movierank"> {{ movie.movie.rank }} </p>
        </div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}